"""updated product model

Revision ID: 25735001ef5d
Revises: f38af0ce48a4
Create Date: 2023-12-14 08:18:43.731271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25735001ef5d'
down_revision = 'f38af0ce48a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
