"""updated models

Revision ID: 5f190704cafd
Revises: 78c945974817
Create Date: 2023-12-19 10:57:00.581147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f190704cafd'
down_revision = '78c945974817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=35), nullable=False))
        batch_op.add_column(sa.Column('order_date', sa.String(length=35), nullable=True))
        batch_op.add_column(sa.Column('carts_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'carts', ['carts_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('carts_id')
        batch_op.drop_column('order_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
