"""updated order model

Revision ID: 78c945974817
Revises: fbde721a44c5
Create Date: 2023-12-18 18:48:36.301292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c945974817'
down_revision = 'fbde721a44c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_carts_id_fkey', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('carts_id')
        batch_op.drop_column('order_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('carts_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=35), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('orders_carts_id_fkey', 'carts', ['carts_id'], ['id'])

    # ### end Alembic commands ###
